server: "hub-cloud.browserstack.com"
user: "shilpasaraf"
key: "1iquWKSsVJqqBqtgwdsu"

common_caps:
  "build": "version1"
  "project": "newintropage"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "browserstack.local": true
    "project": "News"
    "name": "Browser Test"
    "build": "0.1"